Update README.md
HDBSD/Fifos-Patch pull request #1
Opened 2022-07-20 02:10 UTC by DeathMaster001

Fixed grammar and a spelling error.

2022-07-20 17:23 UTC, HDBSD approved these changes
Corrections to readme look good

2022-07-20 17:37 UTC, HDBSD commented on README.md
> +- Implemented primitive testing tools by starting the game with parameter "-HDPatch_Dev"
Looks good, besides this line. Please revert this line back to the original

2022-07-20 17:39 UTC, HDBSD requested changes
Looks good, besides the parameter change, please revert this and we're good to merge

2022-07-20 17:40 UTC, HDBSD commented on README.md
> +- Implemented primitive testing tools by starting the game with parameter "-HDPatch_Dev"
Please revert this line to show "--HDPatch_Dev" again. 

Thanks

2022-07-21 05:03 UTC, DeathMaster001 reviewed
Reverted -- removal

2022-07-21 08:42 UTC, HDBSD approved these changes

2022-07-21 08:42 UTC, HDBSD commented
lgtm

2022-07-21 08:43 UTC, merged